development:
  adapter: postgresql
  encoding: unicode
  database: facebook_card_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: facebook_card_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: facebook_card_production
  pool: 5

